### ISSUE TITLE
Possible gotcha with 2.0.0's Future.init()

### ISSUE THREAD

**Issue by preble** [bignerdranch/Deferred#103]
In 2.0b4 I believe the following code resulted in a filled future:

    let filledVoidFuture = Future<Void>()

...because the `value` parameter was unnamed (`init(_ value: Value)`, [link](https://github.com/bignerdranch/Deferred/blob/v2.0b4/Sources/ExistentialFuture.swift#L85)). In 2.0.0, however, `init()` was added, and so the same code now creates a "future that will never get fulfilled".

I'm not sure this is an "issue" that needs to be resolved in any way, but I thought it worth mentioning here.

**Comment by lyricsboy** [comment]
@zwaldowski any thoughts here? We've got a TODO to upgrade to 2.0 final for our app, and this will affect our code in a spot or two. We can certainly work around it, but if it was a "regression" it might be nice to get a fix in first.

**Comment by zwaldowski** [comment]
I see this as an expected type system interaction; `Future(value: ())` works, perhaps not with the best name. `init(value:)` is no longer unnamed, and it shouldn't have been in the first place. I regret the API regression between 2.0b4 and 2.0.
