### ISSUE TITLE
Replacing or removing fill(_:assertIfFilled:)

### ISSUE THREAD

**Issue by zwaldowski** [bignerdranch/Deferred#105]
Looking to get 👍 or 👎 on dc59e5b2.

See also #101.

**Comment by jeremy-w** [comment]
This appears to remove the ability to fill without asserting. Is that correct, or just the impression given by changeset tunnel vision?

Namewise, `preconditionFill` confused the heck out of me. "It's filling a precondition?" "It asserts something is filled as a precondition?" Naming this seems hard.

**Comment by zwaldowski** [comment]
`fill` still exists.

**Comment by zwaldowski** [comment]
I was (poorly) attempting to follow the pattern of [`dispatchPrecondition`](https://github.com/apple/swift/blob/master/stdlib/public/SDK/Dispatch/Dispatch.swift#L40). I welcome a better name.

**Comment by jeremy-w** [comment]
Yup, changeset tunnel vision, then. :)

I'll think about the name.

**Comment by jeremy-w** [comment]
Ah, the tricky bit is that this needs to atomically test and set (and squeal if the test fails), so it's not a simple "precondition for deferred", but "check this precondition, and if it passes, make it so it won't EVER AGAIN".

Some quick attempts riffing on that:

- `oneTimeFill`
- `fillOnce`
- `preconditionUnfilled(ifPassingFillWith:)`

**Comment by zwaldowski** [comment]
I like `fillOnce`, but I don't like that it doesn't reflect the 💥-iness at the call site.

**Comment by zwaldowski** [comment]
Riffing on yours, maybe `preconditionFilled(with:)` or `precondition(filledWith:)`?

Or maybe `preconditionThatIsHasBeen(filledWith:)`. 😏

**Comment by zwaldowski** [comment]
(I understand `precondition` shouldn't _really_ be a verb in this context, but the stdlib+overlays seem to use it. I don't understand whey they didn't stick with their renames `require` and `requirementFailure`.

**Comment by jeremy-w** [comment]
`dispatchPrecondition` is a declarative statement. Are there some other places where they're using it as a verb? (`require` definitely makes a lot more sense as a verb!)

More ideas:

- `mustFill(with:)`
- `failUnlessFilling(with:)`

Alternatively, could we have `fill` return a yes/no to say if it was the one that did the fill, or even a `enum Fill<T> { case succeeded; case failed(alreadyFilledWith: T); }`? Then you could write something like `precondition(promise.fill(with: value), "promise was already filled!")` in the bool case, or a more sophisticated version for the enum that includes what it was filled with and what you tried to fill it with and does all that for you as `promiseRequire(promise, fillWith: value)` or something like that.

It's the "test and set" combo that is making this so hard, so breaking it apart to the usual test-and-set (fill) and then a "OK, now demand that WE filled it" assertion seems a cleaner way to handle that.

**Comment by jgallagher** [comment]
I don't think `precondition(promise.fill(with: value), "promise was already filled!")` is an option because of how it could interact poorly with compiler optimizations. (I don't believe preconditions are removed in release or unchecked builds, but at least in unchecked, my understanding is that the compiler is free to generate code assuming the precondition will be true.) You'd really need to do the assertion dance of assigning the result into a local then asserting on that, which would be annoying / easy to forget to do. Maaaybe I'm overblowing / misunderstanding this concern?

I want to like `precondition(filledWith:)`, but that sounds too much like "precondition that this _is already_ filled with X". My favorite of the remaining ones is `mustFill(with:)`. If we think this is a rare use, a longer name that seems a little silly is probably ok, like some of the other suggestions here.

**Comment by jgallagher** [comment]
One other thought - if y'all really like `fillOnce`, it's not outside of reasonableness to document the precondition instead of putting it in the name of the method. Plenty of array methods/properties behave that way, for example.

**Comment by zwaldowski** [comment]
@jgallagher's right about the semantics of precondition; that's part of why this boilerplate exists, doing the `if !expr { preconditionFailure() }` dance.

Either way you read it, `Deferred<Int>.preconditionFilled(with: 5)` says "Required that the Promise _was_ filled with 5".

That said, I am being brought around to `mustFill(with:)`. My overall concern is conciseness, but also not being chosen on accident over `fill(with:)`.

(I halfway want to spite you all and make plain `fill(with:)` into `Void?` so you can just `!` it. 😑)

**Comment by jgallagher** [comment]
> I halfway want to spite you all and make plain fill(with:) into Void? so you can just ! it. 😑

Hah, I almost suggested the exact same thing.

**Comment by jeremy-w** [comment]
I think that's kind of wonderfully elegant. There's no chance we could just
throw the `!` in the method name, is there, and have `fill` vs `fill!`?

--
Jeremy W. Sherman <jeremy@bignerdranch.com>

2016-08-09 12:58 GMT-04:00 John Gallagher <notifications@github.com>:

**Comment by zwaldowski** [comment]
Alas, we cannot.

**Comment by jeremy-w** [comment]
`fill(with:) -> Void?` isn't bad: The "`!` means this can crash your app" instinct is pretty strong at this point. The biggest problem in practice is that, with some common lint configs, you'd have to jump through hoops to disable a "no bangs" lint around a fill-bang.

`mustFill(with:)` avoids that issue, and seems pretty clear in its requirement.

**Comment by zwaldowski** [comment]
`Void?` only makes sense to us. I'll tentatively go with `mustFill(with:)`. This is all an edge case, I don't want it to touch `fill(with:)`.
