### ISSUE TITLE
Task might conflict with Foundation

### ISSUE THREAD

**Issue by zwaldowski** [bignerdranch/Deferred#120]
A problem of the may-actually-be-worse-in-my-head-than-in-reality variety, but `Deferred.Task` shadows `Foundation.Task`. Any generics misuses or error involving `Task` tends to instead error about misuse of the Foundation type instead.

**Comment by wookiee** [comment]
How about `Job`

**Comment by zwaldowski** [comment]
I can never tell if you're being serious anymore

**Comment by Ehrippura** [comment]
module cannot build under release configuration, is that associate with this issue?

An error like this:
`Command failed due to signal: Segmentation fault: 11`

**Comment by zwaldowski** [comment]
@Ehrippura It's not related. Just investigated it though, it appears to be [this Swift bug](https://bugs.swift.org/browse/SR-2623) and I've pushed [a workaround](https://github.com/bignerdranch/Deferred/pull/112/commits/a6fab56193483871e7f30b80e704232b13a5c463). Thanks for reporting it!

**Comment by zwaldowski** [comment]
Does not seem to be an issue in practice for now. I'll reopen if it becomes one…
