### ISSUE TITLE
Fixtures.swift included in podspec

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#127]
It looks like `3.0.0-beta.1` added `Fixtures.swift` to the files to be compiled with the module, which makes compilation brake when building for iOS using Cocoapods. Screenshot [here](https://i.imgur.com/KG71per.png)

This is due to the fact that this file (that imports `XCTest`, which is not allowed on non-test targets) is now on `Sources/TestSupport`, so the podspec picks this file up for compiling the module, since it's in the `Sources` directory.

Let me know if you need any more info on this

**Comment by zwaldowski** [comment]
Whoops. Fixed and re-tagged.

**Comment by piercifani** [comment]
Mmm while I see a new tag, I don't see any new commits that fix this issue. Aren't we missing something here?
