### ISSUE TITLE
3.0.0beta1 is not available on Cocoapods

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#128]
Installation fails with:

```
[!] Unable to satisfy the following requirements:

- `BNRDeferred (= 3.0.0-beta.1)` required by `BSWFoundation (0.2.0)`

None of your spec sources contain a spec satisfying the dependency: `BNRDeferred (= 3.0.0-beta.1)`.
```

**Comment by zwaldowski** [comment]
It's [SR-2623](https://bugs.swift.org/browse/SR-2623). I've pushed [a workaround](https://github.com/bignerdranch/Deferred/pull/112/commits/a6fab56193483871e7f30b80e704232b13a5c463) to [the `swift-3_0` branch](https://github.com/bignerdranch/Deferred/tree/swift-3_0). Thanks for reporting it!

**Comment by zwaldowski** [comment]
Working on it. CocoaPods is having hiccups at the moment.

**Comment by zwaldowski** [comment]
[Here we are!](https://github.com/CocoaPods/Specs/blob/master/Specs/BNRDeferred/3.0.0-beta.1/BNRDeferred.podspec.json).
