### ISSUE TITLE
3.0.0beta1 SEG_FAULTs compiler when archiving

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#129]
When Deferred 3.0b1 is installed using Cocoapods and performing an Archive, the compiler throws a [segmentation fault](https://i.imgur.com/QPwLLQi.png)

You can find a project that reproduces this error here: [YoYo](https://github.com/piercifani/YoYo)

**Comment by zwaldowski** [comment]
It's [SR-2623](https://bugs.swift.org/browse/SR-2623). I've pushed [a workaround](https://github.com/bignerdranch/Deferred/pull/112/commits/a6fab56193483871e7f30b80e704232b13a5c463) to [the `swift-3_0` branch](https://github.com/bignerdranch/Deferred/tree/swift-3_0). Thanks for reporting it!
