### ISSUE TITLE
[3.0.0beta1] Crash on allSucceded

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#130]
Hey guys!

I'm experiencing a [crash](https://i.imgur.com/nmb9XC2.png) on `allSucceded` where it's crashing on calling `adoptChild(_:orphaned:pendingCount:)` on `NSProgress`. The exception states that the reason is: `NSProgress 0x60000032fbe0 was already the child of another progress 0x60800032abe0'`

I can reproduce it 100% of the time on my code but I couldn't make it crash using a simpler project.

**Comment by zwaldowski** [comment]
Investigating, thanks! `allSucceeded` was intended to avoid this precise scenario, but might have a minor syntax screw-up somewhere. Could you describe how you're what the `Task`s involved are doing prior to `allSucceeded`? (i.e., an `andThen` or something.)

**Comment by piercifani** [comment]
I was able to create a [gist](https://gist.github.com/piercifani/f006b01c8d0aec1ca445a1742803dd4c) with this issue, let me know if that helps!

**Comment by zwaldowski** [comment]
It helped a lot, thanks! See the [`swift-3_0`](https://github.com/bignerdranch/Deferred/tree/swift-3_0) branch. I hope to cut a tag soon.
