### ISSUE TITLE
[3.0.0beta1] Crash on observing NSProgress

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#132]
Hello,

Sorry to bug again, but I'm finding another crash when (attempting) to observe the progress of a task. I created a [gist](https://gist.github.com/piercifani/6975feda8664e4d828b2581dda941847) that again reproduces the crash.

Thanks for your time and I can't thank you enough for your work on this library!

**Comment by zwaldowski** [comment]
It's no bother at all.

I'm sorry to say this issue is in the code your posted. `ProgressObserver.observeValue(forKeyPath:of:change:context:)` is implemented as:

```swift
    public func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [String : Any]?, context: UnsafeMutableRawPointer?)
```

In Swift 3.0, at least, it should be:

```swift
    override public func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?)
```

**Comment by piercifani** [comment]
I'm sorry but I'm seeing the [same crash](https://i.imgur.com/TpDvoN8.png). Updated gist with fix to the `observeValue` method [here](https://gist.github.com/piercifani/6975feda8664e4d828b2581dda941847).

**Comment by zwaldowski** [comment]
You started making other changes to the code! 😁

A `Progress` instance needs to be created with the `discreteProgress(totalUnitCount:)` factory method. I'll see what I can do about working around requiring this, or if nothing else documenting it better. Thanks.

**Comment by piercifani** [comment]
Hey Zach! Yes, I did change the code that created the `Progress` instances as a way of trying out different approaches, and it inadvertently got pushed to the gist, sorry about that.

I am still seeing issue in my real app, but for now I think it's related to my code. I'll dig deeper to find that out.

Thanks a lot!

PS: Yeah, it'll be great to have documented how to use the progress tracking feature of `Task`
