### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by zwaldowski** [bignerdranch/Deferred#136]
See [current upload from Swift 3 branch](https://bucket.waldowski.me/BNRDeferred-20161022/index.html).

**Comment by jeremy-w** [comment]
Re: [ExistentialTask's definition of](https://github.com/bignerdranch/Deferred/pull/147/files#diff-deebd2f35481182c501a77dd8ea54a50) `init<Task: FutureType where Task.Value: ResultType, Task.Value.Value == SuccessValue>(_ base: Task, cancellation: ((Void) -> Void)? = nil)`:

> It wasn't clear to me from the docs that the cancellation will *only* be called if base is not a Task delivering the same value as Self. That would surprise me for sure as a dev, and I'd probably mess that up at some point. :\ Is it possible to overload such that we don't take the cancellation param unless we're going to use it?

Also includes docs copypasta about base not being a Task, when that's its type in that ctor!

**Comment by jeremy-w** [comment]
NSProgress adopt child ???:

Double negative - so, "i.e., progress is understood to have a parent"?

(I don't understand what this really means, or why we'd mistrust the iOS 9 behavior.)

Return type also is not documented, or why it returns and how it differs from the receiver.
