### ISSUE TITLE
[3.0.0] Framework fails to compile on Release

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#140]
Downloading the tip of the Swift 3 branch and compiling the framework using the default scheme on release mode fails with this error: ![error](https://i.imgur.com/EWLX0TH.png)

**Comment by zwaldowski** [comment]
I've posted a workaround to the same branch for #138, please check there.

**Comment by piercifani** [comment]
Yep, that latest commit fixes it
