### ISSUE TITLE
Recover and produce a new Task

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#149]
Right now, there is a way to recover from an error and produce a new default value for the `SuccessValue`. I think a way to recover from an error by producing a new `Task` for the same `SuccessValue` would be helpful.

Do you think something like this would be helpful?

```
extension Task {

   public func recover(upon executor: Executor, start startNextTask: @escaping(Error) -> Task<SuccessValue>) -> Task<SuccessValue> {
       
       let future: Future<TaskResult<SuccessValue>> = andThen(upon: executor) { (result) -> Task<SuccessValue> in
           do {
               let value = try result.extract()
               return Task<SuccessValue>(success: value)
           } catch let error {
               return startNextTask(error)
           }
       }
       
       return Task<SuccessValue>(future: future)
   }
}
```

**Comment by zwaldowski** [comment]
Rest assured I haven't forgotten about this!

I'm not finding much precedent in other functional patterns, and how this would fit in overall. Maybe @jgallagher could weigh in? (I understand I'm asking you a glorified naming question here.)

I'm slightly leaning towards snippetizing this as a pattern in our [wiki](https://github.com/bignerdranch/Deferred/wiki), but if you've found a use for it, it's likely to be valuable as an addition to the project. I just need to think on it a bit more.

**Comment by piercifani** [comment]
Yes, I have found a use for this function, I'm actually shipping it in the next release of an app I'm working on.

Some pseudo-code to help you understand the use-case:

```swift
let fetchOrderTask: Task<PurchaseOrder> = {
    if someBusinessMadeUpCondition() {
        let specialUsersOrderTask = self.fetchOrderForSpecialUsers()
        let recoverFromSpecialUsersOrderTask = specialUsersOrderTask.recover(upon: uponQueue, substituting: { (_) -> Task<PurchaseOrder> in
            return self.fetchNormalOrder()
        })
        
        return recoverFromSpecialUsersOrderTask
    } else {
        return self.fetchNormalOrder()
    }
}()

```

I'm not sure about what functional pattern this represents, I'm not the most knowledged in this regard, but I have found this pretty useful.

Thanks!

**Comment by zwaldowski** [comment]
See #162
