### ISSUE TITLE
Does `fillIfUnfulfilled` behave appropriately for `Deferred<Optional<T>>`?

### ISSUE THREAD

**Issue by jeremy-w** [bignerdranch/Deferred#15]
Swift has, uh, issues with `Optional<Optional<T>>`. This needs a test to see.

**Comment by zwaldowski** [comment]
This appears to work as expected, but perhaps the body of `Deferred.fill(_:assertIfFilled:)` could use a `switch` instead to make this clearer (and future-proof, in case the `==` semantics change).

**Comment by zwaldowski** [comment]
Aargh, except in 1.2 `switch` doesn't know the full range of `Bool`.

**Comment by jeremy-w** [comment]
Yes, looks like Swift 2 is correctly peeling away just the outer Optional in `if let`, which was an issue in the past IIRC.
