### ISSUE TITLE
What Task.cancel() does and doesn't do

### ISSUE THREAD

**Issue by preble** [bignerdranch/Deferred#158]
Is it correct that `Task.cancel()` simply sets `isCancelled` and has no other real effect? More specifically, does nothing in the framework check `isCancelled` before executing the task? (I've looked through the code and this seems to be true, but I wanted to verify.)

I ask because I had been assuming (incorrectly, it seems) that if a Task were cancelled before it had begun executing, that it would not be run. Naturally I understand that a task can not be stopped while executing without the programmer checking whether it is cancelled, but it seems reasonable to expect behavior to be similar to `[NS]Operation.cancel()`, which does not execute the operation if it is cancelled before execution begins.

```swift
        let d0 = Deferred<TaskResult<String>>()
        let t0 = Task(future: Future(d0))
        
        let t1 = t0.map(upon: DispatchQueue.global(), transform: { $0 + " hello"})
        t1.cancel()
        
        t0.upon(DispatchQueue.main) { print("t0 completed with \($0)") }
        t1.upon(DispatchQueue.main) { print("t1 completed with \($0)") }
        
        d0.fill(with: .success("hi"))
```

The above demonstrates that both t0 and t1 execute.

A contrasting example with [NS]Operation:

```swift
class SomeOperation: Operation {
    override func main() {
        print("SomeOperation.main() is running")
    }
}

...

func imRunningOnTheMainQueue() {
    let op = SomeOperation()
    OperationQueue.main.addOperation(op)
    op.cancel()
}
```

In this case the operation's main never executes.

Certainly, Task is not the same as Operation, but if this is the intended behavior it would seem like something that should be made very clear in the documentation for `cancel()`, and/or perhaps in the documentation for `Task` itself.

**Comment by zwaldowski** [comment]
`upon` blocks still call during cancellation, as it is expectation cancellation will fill with an appropriate failure like `URLSession` does. This preserves the semantic model of `Deferred` and allows `Task` to effectively communicate cancelation to `Future` and vice-versa. `Task` initializers take a cancellation handler to support this (or the similar property on `Progress`).
