### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by mdmathias** [bignerdranch/Deferred#166]
If following [the docs](https://bignerdranch.github.io/Deferred/getting-started.html), you will end up with a `Package.swift` like so:

```swift
import PackageDescription

let package = Package(
    name: "My Extremely Nerdy App",
    dependencies: [
        .Package(url: "https://github.com/bignerdranch/Deferred.git", majorVersion: 3),
    ]
)
```

Then, using `swift package fetch` in Terminal.app, you will see this error:

> error: The dependency graph could not be satisfied. The package (git@github.com:bignerdranch/Deferred.git) with version tag in range (3.0.0..<3.9223372036854775807.9223372036854775807) is not found. Found tags ([2.0.0-rc.1, 2.0.0, 2.2.0-rc.1, 2.2.0, 2.2.1, 3.0.0-beta.1, 3.0.0-beta.2, 3.0.0-beta.3, 3.0.0-rc.1, 3.0.0-rc.2])

Okay...so I will explicitly specify a `Version` that (I think) has a resolvable release tag.

```swift
import PackageDescription

let package = Package(
    name: "My Extremely Nerdy App",
    dependencies: [
        .Package(url: "https://github.com/bignerdranch/Deferred.git", Version(2,2,1)),
    ]
)
```

But then I get:

> error: the package has an unsupported layout, unexpected source file(s) found: /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/BlockCancellableTaskTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/DeferredTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/ExistentialFutureTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/Fixtures.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/FutureCustomExecutorTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/IgnoringFutureTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/LockProtectedTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/ReadWriteLockTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/ResultRecoveryTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/TaskAccumulatorTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/TaskResultTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/TaskTests.swift, /Users/DubbaDubs/Documents/BNR Books/AdvancedSwift/Networking/Deferred/Solution/SWAPI/Packages/Deferred-2.2.1/Tests/VoidResultTests.swift
fix: move the file(s) inside a module

I think the tests for Deferred need to have a different directory structure. Right now it is, `.../Tests/allOfTheTests.swift`. I believe it will need to be `.../Tests/DeferredTests/allOfTheTests.swift`.

This is the structure on master right now, which I imagine is reflected in all of the 3.0.0 pre-releases as well.

**Comment by mdmathias** [comment]
I think the docs for Swift Package Manager need to be updated to something like this 

`.Package(url: "git@github.com:bignerdranch/Deferred.git", Version(3,0,0, prereleaseIdentifiers: ["rc", "2"]))` since Deferred 3.0 isn't out of prerelease.

**Comment by zwaldowski** [comment]
See #167
