### ISSUE TITLE
Can't compile with Cocoapods

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#175]
I noticed that there was a re-tag of the releases, after this I cannot compile when using Cocoapods

![](https://i.imgur.com/FH24yc3.jpg)

Any workaround?

**Comment by zwaldowski** [comment]
`pod lib lint` works fine locally and for integrating into a test project locally. Can you upload that sample project that's failing somewhere? Otherwise, let me attempt pushing to `pod trunk`.

**Comment by piercifani** [comment]
There [you go](https://www.dropbox.com/s/s130e5k9cd739a0/Workshop.zip?dl=0)

**Comment by zwaldowski** [comment]
Dropbox says it's gone! :(

**Comment by piercifani** [comment]
Damn, try again [please](https://www.dropbox.com/s/s130e5k9cd739a0/Workshop.zip?dl=0)

**Comment by zwaldowski** [comment]
I don't think this is us, it seems to be brand new. I'm sorry! 🙍 Setting `SWIFT_ACTIVE_COMPILATION_CONDITIONS` to `$(inherited) DEBUG` for the `BNRDeferred` framework target worked in your project. See also CocoaPods/CocoaPods#6625.

**Comment by piercifani** [comment]
😢 

Thanks a lot for the quick response! I will add `$(inherited)` for now until they sort it out

**Comment by piercifani** [comment]
For anyone out there with this issue, while Cocoapods figures this out on their end, add this to your `Podfile`:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'BNRDeferred'
          config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = "$(inherited) DEBUG"
      end
    end
  end
end
```

**Comment by ShenYj** [comment]
> For anyone out there with this issue, while Cocoapods figures this out on their end, add this to your `Podfile`:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       if target.name == 'BNRDeferred'
>           config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = "$(inherited) DEBUG"
>       end
>     end
>   end
> end
> ```

it's helpful for me
