### ISSUE TITLE
TestSupport will not build on Ubuntu 14

### ISSUE THREAD

**Issue by vikingjs** [bignerdranch/Deferred#177]
When trying to build my project on a heroku-like remote server I don't control, I get a bunch of errors similar to this:

/build/app/.build/release/TestSupport.build/Fixtures.swift.o:/build/app/.build/release/TestSupport.build/Fixtures.swift.o:_TMfC11TestSupport22CustomExecutorTestCase: error: undefined reference to '_TFC6XCTest6XCTestg7testRunGSqCS_9XCTestRun_'

I'm unable to (simply) remove TestSupport from the project because it's using Swift Package Manager to pull from here. I'm using Deferred version 3.0.0

**Comment by zwaldowski** [comment]
I'm afraid this has to do with the following:

- https://bugs.swift.org/browse/SR-3034
- https://github.com/apple/swift/pull/6428
- apple/swift-package-manager#758

Some strategies I can think of:

- Update your buildpack to Swift 3.0.1 or 3.1.
- If you can control the SwiftPM command-line arguments, try adding `-Xswiftc -enable-testing`.
- If you simply cannot mitigate any other way, remove Deferred's tests and their entries in the `Package.swift` file.

I'm sorry for the inconvenience. I'm not sure there's much we can do on our end to mitigate this problem.
