### ISSUE TITLE
Add Deferred to Apple's Swift Source Compatibility CI

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#178]
Apple released a [Source Compatibility CI](https://swift.org/source-compatibility/) to detect regression in Source Compatibility, which I think is an awesome idea.

Being Deferred a great example of a complex, yet compact codebase that takes Swift to the next level, I strongly feel like it'll be a good idea to add it to the open source projects it's tested against.

Do you guys think it can be a good idea to add it, since it already fulfils all of the requirements to be added?

**Comment by zwaldowski** [comment]
We'll branch the 3.0.0 tag (or master, I guess; #176 is only making light use of 3.1 features`) as a `swift-3` branch.

**Comment by zwaldowski** [comment]
With 3.1.0 tagged, this should be doable soon.

**Comment by zwaldowski** [comment]
See apple/swift-source-compat-suite#133.
