### ISSUE TITLE
rename `Deferred` to `Eventually`?

### ISSUE THREAD

**Issue by jeremy-w** [bignerdranch/Deferred#18]
I think the name would be more suggestive of the semantics if `Deferred` were named `Eventually`.

If we separate the future value from the ability to fill it, we'd likely have an internal `Deferred` with public "faces" `Eventually<Value>` and `Resolve<Value>`. I'm not sold on the `Resolve` bit – `Determine`, `Fix`, `Produce`, `Supply`. `Resolve` has the advantage that you can `resolve.to(v)`, though.

**Comment by zwaldowski** [comment]
Any movement on this?

**Comment by jeremy-w** [comment]
I haven't written any code, if that's the question. :)

Are we still interested in changing it (and possibly renaming the project from Deferred, since that name would no longer apply)? There's been another quarter of usage and work on the project since the issue was opened, and things seem a bit more solid now.

**Comment by zwaldowski** [comment]
It's a branding choice at this point. Re-open for any concerns.

**Comment by jeremy-w** [comment]
Agreeing with closure, but with some closing thoughts. :)

Looking at this with fresh eyes - deferred is a weird name. It's like, "Yeah, we could do it now, but we decided to put it off."

We could rename the type without renaming the library containing it, so it needn't affect library branding.

That said, you quickly become used to the `Deferred` bit, and now that we have `Future`, you hardly see `Deferred` in type signatures, so it's less of an issue than ever.

**Comment by zwaldowski** [comment]
We might be able to revisit the network of names in the Swift 3 time period. If we don't get better existentials (or even if we do), we'll have to reconsider the names of `FutureType` and everything involved.
