### ISSUE TITLE
Build failure using CocoaPods

### ISSUE THREAD

**Issue by lyricsboy** [bignerdranch/Deferred#185]
I'm using Deferred 3.1 in a new project via CocoaPods.

When it tries to build the BNRDeferred Pod, I get the following errors:

```
.../Pods/BNRDeferred/Sources/Deferred/Deferred.swift:138:60: Use of undeclared type 'UnsafeAtomicRawPointer'
.../Pods/BNRDeferred/Sources/Task/TaskProgress.swift:116:29: Use of unresolved identifier 'UnsafeAtomicBitmask'
.../Pods/BNRDeferred/Sources/Deferred/Locking.swift:69:24: Use of unresolved identifier 'UnsafeNativeLock'
```

I think the issue relates to the `SWIFT_ACTIVE_COMPILATION_CONDITIONS` build setting not containing `XCODE`. Here's a screen shot of the settings Xcode shows for that in the BNRDeferred target of my Pods project:

![screen shot 2017-06-03 at 11 39 12 am](https://cloud.githubusercontent.com/assets/36460/26754970/6961c794-4852-11e7-96d6-9582ae60e36e.png)

Seems like it needs to be made to inherit that setting from the config file, somehow. Not sure if this is a Deferred problem or a CocoaPods problem.

**Comment by lyricsboy** [comment]
Same issue in 3.0, as well.

**Comment by lyricsboy** [comment]
3.0.0-rc.1, the last version before the XCODE setting was introduced, builds properly via CocoaPods.

**Comment by zwaldowski** [comment]
See #175 and CocoaPods/CocoaPods#6625.

**Comment by lyricsboy** [comment]
Thanks. That's gross.
