### ISSUE TITLE
Retriable Tasks

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#191]
Is this something that should ship with this library or something that clients should implement?

I have a sample implementation here in case you think it would be useful to ship with it:

```swift

extension Task {
  static func retriableTask(
    maxFailures: Int = 3,
    executor: PreferredExecutor = DispatchQueue.main,
    shouldRetry: @escaping (Error) -> Bool = { _ in return true },
    generator: @escaping (Void) -> Task<SuccessValue>) -> Task<SuccessValue> {
    let originalTask = generator()
    var lastFailedTask = originalTask
    for _ in 0..<maxFailures {
      let newTask = lastFailedTask.fallback(upon: executor, to: { error -> Task<SuccessValue> in
        guard shouldRetry(error) else {
          return Task(failure: error)
        }

        return generator()
      })
      lastFailedTask = newTask
    }
    return lastFailedTask
  }
}
```

**Comment by zwaldowski** [comment]
I'll discuss it among my team! It seems very useful, but I'm sure where we'd put customization points to make sure it stays flexible. If nothing else, I'd live for us to maintain some patterns on the [wiki](https://github.com/bignerdranch/Deferred/wiki).

**Comment by zwaldowski** [comment]
I know this has taken ridiculously long time to look at, it's nice and I think I'll integrate it. Slotted for next major release.

**Comment by jaredsinclair** [comment]
Would this retry include an optional exponential backoff? I imagine a common use case is retrying a failed network request, which oftentimes needs a delay to succeed (overcoming transient loss of a network, e.g.).

**Comment by zwaldowski** [comment]
@jaredsinclair That'd be neat! But I want to make it clear the intent for this convenience would not be as a general-purpose networking tool.
