### ISSUE TITLE
Can't compile with Cocoapods 1.5.0

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#218]
When trying out the new Cocoapods (default) build setting, using static libraries, Deferred won't compile since there seems to be a problem with it's `modulemap`

![](https://i.imgur.com/mbAUIs3.png)

**Comment by zwaldowski** [comment]
Odd, CP is doing something to rewrite ours. Let me investigate.

**Comment by zwaldowski** [comment]
See CocoaPods/CocoaPods#7585.

**Comment by zwaldowski** [comment]
While 7585 is definitely related, I've filed a more specific CocoaPods/CocoaPods#7726. Depending on the feedback there I can switch up the submodule a bit, but I'd really rather have our pod align with the same way the Xcode project is built.

**Comment by zwaldowski** [comment]
Worked around in #232. I'll be cutting that as a 3.3.x release shortly once I figure something out re: #230.
