### ISSUE TITLE
How to correctly track a Task's progress?

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#260]
Hi there!

I've written a URLSession extension that allows you to upload a file and wrap it in a task like this:

```
extension URLSession {

  public func uploadFile(with urlRequest: URLRequest, fileURL: URL) -> Task<APIClient.Response> {
    
    let deferred = Deferred<Task<APIClient.Response>.Result>()
    let uploadTask = self.uploadTask(with: urlRequest, fromFile: fileURL) { (data, response, error) in
      self.analyzeResponse(deferred: deferred, data: data, response: response, error: error)
    }
    uploadTask.resume()
    if #available(iOS 11.0, tvOS 11.0, watchOS 4.0, macOS 10.13, *) {
      return Task(deferred, progress: uploadTask.progress)
    } else {
      return Task(deferred, cancellation: { [weak uploadTask] in
        uploadTask?.cancel()
      })
    }
  }
}
```

As you see, I'm using the `URLSessionUploadTask`'s progress to initialise the Task. After that, I'm using `andThen` to parse the JSON response from the server and more cleanup.

However, when observing the progress, the upload task is merely a fraction of the total progress, not corresponding to the much more heavier task that it represents.

How should we proceed in such cases? I realise this is more a `NSProgress` question than a Deferred question, but maybe someone can shed some light on this. You can see this behaviour in [this commit](https://github.com/theleftbit/BSWFoundation/commit/c2b86c9d3b7ad7ea4002bac24bac7da4d657d19f) of my project which is based on BNRDeferred

BTW: Really looking forward to version 4.0 of Deferred 💪

**Comment by piercifani** [comment]
Whoops, just saw https://github.com/bignerdranch/Deferred/pull/259, I'll be following that instead

**Comment by piercifani** [comment]
BTW: I updated my project to use the latest from master and I am seeing a difference in progress report, however the change is not exactly what I'm looking for: The `fractionCompleted` property is starting at 0.8 and then climbing all the way to 1.0, but it's still not yet correct IMHO. Maybe I'm doing something wrong?

**Comment by zwaldowski** [comment]
The snippet you've provided reflects something I'd expect #259 to track correctly, as it was made while debugging an identical upload task (ping @DrewFitz?).

**Comment by zwaldowski** [comment]
Thanks, that's quite helpful!

Task's progress assumes that the "original" task is a larger piece of the job, and chaining done on it forms a smaller part. That assumption is non-ideal in your network request method. At a high level, I recommend performing one's `andThen` around the larger chunks of the job it would make sense to show up in the progress. However, I don't recommend changing what you have, as the functional chaining you've done is quite nice. 😃 I'll keep iterating on a better way to do this formula.

**Comment by zwaldowski** [comment]
I haven't been able to return to it until very recently. I hope to have something today, and I'm sorry if that's too late for you.

**Comment by piercifani** [comment]
No worries Zach, I completely understand! Thanks a lot for your effort

**Comment by zwaldowski** [comment]
#265 should get you out of the woods. I've filed some secondary improvements into #267 before I tag a next beta, but please give it a whirl. Thank you for your patience!

**Comment by piercifani** [comment]
No @zwaldowski, thank YOU!
