### ISSUE TITLE
Using a Task's progress after an `andThen` 

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#281]
Hey guys,

I'm again having some issues when observing a Task's progress if the larger chunk of it it's done in an `andThen` block. In the following snippet, the `fractionCompleted` of the outer Task (called `finalTask`) jumps from 0.057 to 0.96 and stalls there until the bigger chunk is completed. However the `uploadTask`'s progress is correctly tracked.

```swift
    func testGetAndUpload() throws {

        let getTask = sut.fetchData()
        let finalTask = getTask.andThen(upon: .main) { _ -> Task<VoidResponse> in
            let uploadTask = self.sut.uploadVideo(videoURL)
            var uploadProgress: ProgressObserver! = ProgressObserver(progress: uploadTask.progress) { (progress) in
                print("UploadTask \(progress.fractionCompleted)")
            }
            uploadTask.upon(.main, execute: { (_) in
                uploadProgress = nil
            })
            return uploadTask
        }

        var completeTaskProgress: ProgressObserver! = ProgressObserver(progress: finalTask.progress) { (progress) in
            print("CompleteTask \(progress.fractionCompleted)")
        }
        let _ = try self.waitAndExtractValue(finalTask, timeout: 10)
        completeTaskProgress = nil
    }
```

The previous code is extracted from the `testGetAndUpload` in 
https://github.com/theleftbit/BSWFoundation/tree/progress-reporting, feel free to clone and execute this test to check on the command line the results.

**Comment by piercifani** [comment]
Hey guys, any news on this issue? And about the Swift 5 release: when will that be tagged and called final?

**Comment by zwaldowski** [comment]
I'll have an update today, thanks!

**Comment by piercifani** [comment]
Much better! Thanks a log @zwaldowski!!!
