### ISSUE TITLE
Canonical examples for how to use `andThen`

### ISSUE THREAD

**Issue by markd2** [bignerdranch/Deferred#288]
Hi!  It'd be nice to have canonical examples on how to use `andThen`.  There was recently an extended Slack chat about using `andThen`, with suggestions about defeating type inference, the use of `try` causing odd errors, and then questions on how to propagate errors out in to the result that anyone who `upons` peels apart.  It'd be nice if there were a canonical example of its use we can crib from and expand.  `andThen` is mentioned a couple of times in the intro docs, but not an actual use that I could find.

**Comment by zwaldowski** [comment]
Absolutely. Will do. Soon. :)
