### ISSUE TITLE
Improve the documentation comments and generate HTML docs

### ISSUE THREAD

**Issue by lyricsboy** [bignerdranch/Deferred#44]
The doc comments should be updated and expanded for new users.

We can publish a nicely formatted docset as a github pages site associated with this repo.

**Comment by zwaldowski** [comment]
As mentioned in #22, the use of [jazzy](https://github.com/realm/jazzy) handles a lot of the web end of things.

```shell
jazzy -m Deferred -g https://github.com/bignerdranch/Deferred -a "Big Nerd Ranch" -u https://github.com/bignerdranch --module-version=2.0.0 -r http://bignerdranch.github.io/Deferred/docs/ --swift-version 2.1
```

**Comment by zwaldowski** [comment]
I've published the docs from the tip of #38 to the [repo's GitHub Pages endpoint](http://bignerdranch.github.io/Deferred/) as an example. It's pretty spiffy, and 100% documented!

I'm not sure how we ultimately want to handle this; should the GitHub Pages site be the current docs from `master`? Or do we keep archival versions? (Realm, for instance, does [the latter](https://github.com/realm/realm-cocoa/blob/master/scripts/build-docs.sh).)

How we decide to implement it changes the level to which we can automate it. The workflow is currently all manual, but we could potentially [get Travis to do it](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) when we merge stuff to `master`.

**Comment by zwaldowski** [comment]
Updated to the tip of #29 now that #30 is merged. [Check it out!](http://bignerdranch.github.io/Deferred/)

**Comment by zwaldowski** [comment]
bignerdranch/CoreDataStack#42 is also relevant!

**Comment by zwaldowski** [comment]
Completed in #53.
