### ISSUE TITLE
CocoaPods Support

### ISSUE THREAD

**Issue by BalestraPatrick** [bignerdranch/Deferred#63]
Hello,

In the Readme it's specified that the project doesn't support CocoaPods but the repository contains a `.podspec` file. When trying to install it with `pod 'Deferred'`, another pod with the same name is installed. Do you have any idea about what's going on?

Thanks a lot!

**Comment by zwaldowski** [comment]
Since 2.0 is in beta, we were waiting to get some more internal feedback. I've pulled the trigger, though, by tagging Beta 4. We're [BNRDeferred](https://cocoapods.org/pods/BNRDeferred) on CocoaPods. Thanks!

**Comment by BalestraPatrick** [comment]
Perfect, thanks a lot!
