### ISSUE TITLE
[README] Explain Future and Promise Types

### ISSUE THREAD

**Issue by randomstep** [bignerdranch/Deferred#70]
Deferred preferred interface is through Future and Promise Types. We should update the README to point people toward this usage and appropriate documentation.

Short version: Future and Promise split the 2 sides of the Deferred API. Future is read-only, Promise is write-only. So you make a Deferred, ensure the Promise view has only one owner, and give the Future out to anyone that wants it.

**Comment by zwaldowski** [comment]
In order to follow The Law of Conservation of Existing Sections of the README, doing an additive approach until we can come back and weave `Future` into the narrative more.
